#!/bin/bash

mkdir obj
prev=20
prev_d=d_gauss

for x in 10 30 40 50
do
	for i in 10 20 30 40 50 60 70 80 90
	do
		echo "size=$i and amount=$x\n" >> out
		amount_o="amount = $prev"
		amount_n="amount = $x"
		gauss_n="d_gauss_$x"
		git checkout test-$i
		sed "s/${prev_d}/${gauss_n}/g" src/main.cpp -i
		sed "s/${amount_o}/${amount_n}/g" src/main.cpp -i
		make
		./blur >> out
		git add --all
		git commit -m "$x"
		prev_d="d_gauss_$x"
	done

	prev=$x

done
